export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_STOCK = "UPDATE_STOCK";
export const UPDATE_PRODUCT_STOCK = "UPDATE_PRODUCT_STOCK";
export const FETCH_SEARCH_PRODUCT = "FETCH_SEARCH_PRODUCT";